services:
  frontend:
    build:
      context: ../.
      dockerfile: dockerfiles/Dockerfile.dev.frontend
    volumes:
      - ../src/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ../src/frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    
volumes:
  pgdata:
