services:
  nginx:
    build:
      context: ../.
      dockerfile: dockerfiles/Dockerfile.nginx
    ports:
      - "80:80"
      # Remove when used live
      # - "443:443"
    volumes: 
      - static_volume:/app/staticfiles
    networks:
      - hive-net
    depends_on:
      - backend


  backend:
    build:
      context: ../.
      dockerfile: dockerfiles/Dockerfile
    command: |
      sh -c "
      python manage.py migrate &&
      python3 manage.py collectstatic --noinput &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8080
      "
    expose:
     - "8080"
    env_file:
      - ../src/services/.env
    environment:
      - ENV=production
      - DEBUG=False
    volumes: 
      - static_volume:/app/staticfiles
    networks:
      - hive-net
    depends_on:
      - db   

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - hive-net

volumes:
  pgdata:
  static_volume:

networks:
  hive-net: