services:
  nginx:
    build:
      context: ../.
      dockerfile: dockerfiles/Dockerfile.nginx
    image: nginx:ci-${COMMIT_SHA} # Dynamic tag for CI/CD Flows
    ports:
      - "80:80"
      # Remove when used live
      # - "443:443"
    volumes: 
      - static_volume:/app/staticfiles
    networks:
      - creamline-net
    depends_on:
      - backend


  backend:
    build:
      context: ../.
      dockerfile: dockerfiles/Dockerfile
    image: backend:ci-${COMMIT_SHA} # Dynamic tag for CI/CD Flows
    command: |
      sh -c "
      django-admin compilemessages &&
      python3 manage.py migrate &&
      python3 manage.py collectstatic --noinput &&
      gunicorn backend.wsgi:application --bind 0.0.0.0:8080
      "
    expose:
     - "8080"
    env_file:
      - ../src/services/.env
    environment:
      - ENV=production
      - DEBUG=False
    volumes: 
      - static_volume:/app/staticfiles
    networks:
      - creamline-net
    depends_on:
      - db   

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - creamline-net

volumes:
  pgdata:
  static_volume:

networks:
  creamline-net: