services:
  backend:
    image: python:3.13-alpine
    working_dir: /app
    command: |
      sh -c "
      pip install --root-user-action=ignore -r requirements.txt &&
      python /app/manage.py migrate &&
      python /app/manage.py runserver 0.0.0.0:8000
      "    
    ports:
      - "8000:8000"
    volumes:
      - ../src/services:/app
    env_file:
      - ../src/services/.env
    environment:
      - DEBUG=True
      - ENV=development
    depends_on:
      - db

  email-creator:
    image: node:24.2-alpine
    working_dir: /app
    command: sh -c "
      npm install && npm run dev
      "
    volumes:
      - ../src/email-creator:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ../src/email-creator/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENV=development
    depends_on:
      - backend
    
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
