services:
  backend:
    build:
      context: ../.
      dockerfile: dockerfiles/Dockerfile
    command: |
      sh -c "
      django-admin compilemessages &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "    
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ../src/services:/app
    env_file:
      - ../src/services/.env
    environment:
      - DEBUG=True
      - ENV=development
    depends_on:
      - db

  frontend:
    image: node:24.2-alpine
    working_dir: /app
    command: sh -c "
      npm ci --silent && npm run dev
      "
    volumes:
      - ../src/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - ../src/frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - ENV=development
    depends_on:
      - backend
    
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
